type StoreBranch = 'Balwyn' | 'Cheltenham' | 'Essendon' | 'Malvern' | 'Mobile'

export type SchoolBranch =
    | 'Blackburn Primary'
    | 'Chalcot Lodge'
    | 'Malvern Primary'
    | 'Elwood Primary'
    | 'Elsternwick Primary'
    | 'St Michaels Grammar'
    | 'Heany Park Primary'
    | 'McKinnon Primary'
    | 'Hughesdale'
    | 'Abbotsford Primary'
    | 'Auburn Primary'
    | 'Burwood East Primary'
    | 'Flemington Primary'
    | 'Hampton Primary'
    | 'Huntingdale Primary'
    | 'Karoo Primary'
    | 'Malvern Valley Primary'
    | 'Oakleigh Grammar'
    | 'Old Orchard Primary'
    | 'Ripponlea Primary'
    | 'St Kilda Primary'
    | 'East Bentleigh Primary'
    | 'King David'
    | 'Our Lady of Good Counsel'
    | 'Holy Family Primary'
    | 'TEST'

export type Branch = StoreBranch | SchoolBranch
