export enum Additions {
    chickenNuggets = 'chickenNuggets',
    fairyBread = 'fairyBread',
    glutenFreeFairyBread = 'glutenFreeFairyBread',
    fruitPlatter = 'fruitPlatter',
    frankfurts = 'frankfurts',
    sandwichPlatter = 'sandwichPlatter',
    vegetarianSpringRolls = 'vegetarianSpringRolls',
    veggiePlatter = 'veggiePlatter',
    vegetarianQuiche = 'vegetarianQuiche',
    watermelonPlatter = 'watermelonPlatter',
    potatoGems = 'potatoGems',
    wedges = 'wedges',
    lollyBags = 'lollyBags',
    grazingPlatterMedium = 'grazingPlatterMedium',
    grazingPlatterLarge = 'grazingPlatterLarge',
    volcanoPartyPack = 'volcanoPartyPack',
    lipBalmPartyPack = 'lipBalmPartyPack',
    dinosaurBathBombPartyPack = 'dinosaurBathBombPartyPack',
    slimePartyPack = 'slimePartyPack',
}
