import { Creations } from './Creations'

export type CreationKeyMap = { [key in keyof typeof Creations]: string }

export const CreationDisplayValuesMap: CreationKeyMap = {
    [Creations.fairyBathBombs]: 'Fairy Bath-Bombs',
    [Creations.glitterFacePaint]: 'Glitter Face Paint',
    [Creations.rainbowBathCrystals]: 'Rainbow Bath Crystals',
    [Creations.rainbowSoap]: 'Rainbow Soap',
    [Creations.lipBalm]: 'Sparkling Lip-Balm',
    [Creations.perfume]: 'Shining Perfume',
    [Creations.soap]: 'Sparkling Soap',
    [Creations.lavaLamps]: 'Lava Lamps',
    [Creations.bugsInSoap]: 'Bugs in Soap',
    [Creations.bathBombs]: 'Fizzy Bath Bombs',
    [Creations.galaxySoap]: 'Galaxy Soap',
    [Creations.monsterSlime]: 'Monster Slime',
    [Creations.wobblySoap]: 'Wobbly Soap',
    [Creations.fluffySlime]: 'Fluffy Slime',
    [Creations.galaxySlime]: 'Galaxy Slime',
    [Creations.glitterSlime]: 'Glitter Slime',
    [Creations.crunchySlime]: 'Crunchy Slime',
    [Creations.fairySlime]: 'Fairy Glitter Slime',
    [Creations.expertGalaxySlime]: 'Expert Galaxy Slime',
    [Creations.expertRainbowBathBombs]: 'Expert Rainbow Bath-Bombs',
    [Creations.expertCrunchySlime]: 'Expert Crunchy Slime',
    [Creations.expertRainbowSlime]: 'Expert Rainbow Slime',
    [Creations.expertRainbowSoap]: 'Expert Rainbow Soap',
    [Creations.expertWatermelonBathBombs]: 'Expert Watermelon Bath-Bombs',
    [Creations.expertGalaxyBathBombs]: 'Expert Galaxy Bath-Bombs',
    [Creations.unicornSoap]: 'Unicorn Soap',
    [Creations.rainbowBathBombs]: 'Rainbow Bath Bombs',
    [Creations.volcanoes]: 'Bubbling Volcanoes',
    [Creations.wobblyGalaxySoap]: 'Wobbly Galaxy Soap',
    [Creations.instantSnowSlime]: 'Instant Snow Slime',
    [Creations.magicSand]: 'Magic Sand',
    [Creations.wobblyStarSoap]: 'Wobbly Star Soap',
    [Creations.unicornSlime]: 'Unicorn Slime',
    [Creations.rainbowSlime]: 'Rainbow Slime',
    [Creations.frozenSparkleSlime]: 'Frozen Sparkle Slime',
    [Creations.animalSoap]: 'Animal Soap',
    [Creations.animalsInSoap]: 'Animals in Soap',
    [Creations.lavaBathCrystals]: 'Lava Bath Crystals',
    [Creations.magicQuickSand]: 'Magic Quick Sand',
    [Creations.animalsInBathBombs]: 'Animals in Bath Bombs',
    [Creations.unicornGlitterShimmer]: 'Unicorn Glitter Shimmer',
    [Creations.unicornGalaxySlime]: 'Unicorn Galaxy Slime',
    [Creations.unicornBathCrystals]: 'Unicorn Bath Crystals',
    [Creations.unicornBathShimmer]: 'Unicorn Bath Shimmer',
    [Creations.unicornBubbleBath]: 'Unicorn Bubble Bath',
    [Creations.butterflySoap]: 'Butterfly Soap',
    [Creations.unicornBathBombs]: 'Unicorn Bath Bombs',
    [Creations.tieDyeSoap]: 'Tie Dye Soap',
    [Creations.tieDyePillow]: 'Tie Dye Pillow',
    [Creations.marbleCrystals]: 'Marble Crystals',
    [Creations.tieDyeScrunchie]: 'Tie Dye Scrunchie',
    [Creations.tieDyeToteBags]: 'Tie Dye Tote Bags',
    [Creations.tieDyeSocks]: 'Tie Dye Socks',
    [Creations.bugsInBathBombs]: 'Bugs in Bath Bombs',
    [Creations.sandSlime]: 'Sand Slime',
    [Creations.sugarScrubLipBalm]: 'Sugar Lip Scrub',
    [Creations.mermaidSugarScrub]: 'Mermaid Sugar Scrub',
    [Creations.goldSlime]: 'Gold Slime',
    [Creations.speakNowPurpleBathbombs]: "'Speak Now' Purple Bath Bombs",
    [Creations.evermoreSlime]: 'Evermore Slime',
    [Creations.folkloreButterflySoap]: 'Folklore Butterfly Soap',
    [Creations.friendshipBracelets]: 'Friendship Bracelets',
    [Creations.loverRainbowBathBombs]: "'Lover' Rainbow Bath Bombs",
    [Creations.fearlessGoldSlime]: 'Fearless Gold Slim',
    [Creations.midnightsSlime]: 'Midnights Slime',
    [Creations.red1989LipBalm]: 'Red 1989 Lip Balm',
    [Creations.loverGlitterFacePaint]: "'Lover' Glitter Face Paint",
}
