export const Fields = {
    PARENT_FIRST_NAME: "parentFirstName",
    PARENT_LAST_NAME: "parentLastName",
    PARENT_EMAIL: "parentEmail",
    PARENT_MOBILE: "parentMobile",
    CHILD_NAME: "childName",
    CHILD_AGE: "childAge",
    DATE: "date",
    TIME: "time",
    LOCATION: "location",
    PARTY_LENGTH: "partyLength",
    ADDRESS: "address",
    NUMBER_OF_CHILDREN: "numberOfChildren",
    NOTES: "notes",
    CREATION_1: "creation1",
    CREATION_2: "creation2",
    CREATION_3: "creation3",
    CAKE: "cake",
    CAKE_FLAVOUR: "cakeFlavour",
    QUESTIONS: "questions",
    FUN_FACTS: "funFacts"
}

export const Locations = {
    BALWYN: "balwyn",
    ESSENDON: "essendon",
    MALVERN: "malvern",
    MOBILE: "mobile"
}

export const CakeFlavours = {
    CHOCOLATE: "chocolate",
    VANILLA: "vanilla"
}

export const Additions = {
    CHICKEN_NUGGETS: "chickenNuggets",
    FAIRY_BREAD: "fairyBread",
    FRUIT_PLATTER: "fruitPlatter",
    SANDWICH_PLATTER: "sandwichPlatter",
    VEGGIE_PLATTER: "veggiePlatter",
    WATERMELON_PLATTER: "watermelonPlatter",
    WEDGES: "wedges",
    LOLLY_BAGS: "lollyBags"
}

export const Creations = {
    FAIRY_BATH_BOMBS: "fairyBathBombs",
    GLITTER_FACE_PAINT: "glitterFacePaint",
    RAINBOW_BATH_CRYSTALS: "rainbowBathCrystals",
    RAINBOW_SOAP: "rainbowSoap",
    LIP_BALM: "lipBalm",
    PERFUME: "perfume",
    SOAP: "soap",
    LAVA_LAMPS: "lavaLamps",
    BUGS_IN_SOAP: "bugsInSoap",
    BATH_BOMBS: "bathBombs",
    GALAXY_SOAP: "galaxySoap",
    WOBBLY_SOAP: "wobblySoap",
    MONSTER_SLIME: "monsterSlime",
    FLUFFY_SLIME: "fluffySlime",
    GALAXY_SLIME: "galaxySlime",
    GLITTER_SLIME: "glitterSlime",
    CRUNCHY_SLIME: "crunchySlime",
    FAIRY_SLIME: "fairySlime",
    EXPERT_GALAXY_SLIME: "expertGalaxySlime",
    EXPERT_RAINBOW_BATH_BOMBS: "expertRainbowBathBombs",
    EXPERT_CRUNCHY_SLIME: "expertCrunchySlime",
    EXPERT_RAINBOW_SLIME: "expertRainbowSlime",
    EXPERT_RAINBOW_SOAP: "expertRainbowSoap",
    EXPERT_WATERMELON_BATH_BOMBS: "expertWatermelonBathBombs",
    EXPERT_GALAXY_BATH_BOMBS: "expertGalaxyBathBombs",
    // added after website and packages rebuilt
    UNICORN_SOAP: "unicornSoap",
    RAINBOW_BATH_BOMBS: "rainbowBathBombs",
    VOLCANOES: "volcanoes",
    WOBBLY_GALAXY_SOAP: "wobblyGalaxySoap",
    INSTANT_SNOW_SLIME: "instantSnowSlime",
    MAGIC_SAND: "magicSand",
    WOBBLY_STAR_SOAP: "wobblyStarSoap",
    UNICORN_SLIME: "unicornSlime",
    RAINBOW_SLIME: "rainbowSlime",
    FROZEN_SPARKLE_SLIME: "frozenSparkleSlime",
    ANIMALS_IN_SOAP: "animalsInSoap",
    LAVA_BATH_CRYSTALS: "lavaBathCrystals",
    MAGIC_QUICK_SAND: "magicQuickSand",
    ANIMALS_IN_BATH_BOMBS: "animalsInBathBombs",
    UNICORN_GLITTER_SHIMMER: "unicornGlitterShimmer",
    UNICORN_GALAXY_SLIME: "unicornGalaxySlime",
    UNICORN_BATH_CRYSTALS: "unicornBathCrystals",
    UNICORN_BATH_SHIMMER: "unicornBathShimmer",
    UNICORN_BUBBLE_BATH: "unicornBubbleBath",
    BUTTERFLY_SOAP: "butterflySoap",
    UNICORN_BATH_BOMBS: "unicornBathBombs",
    TIE_DYE_SOAP: "tieDyeSoap",
    TIE_DYE_PILLOW: "tieDyePillow",
    MARBLE_CRYSTALS: "marbleCrystals",
    TIE_DYE_SCRUNCHIE: "tieDyeScrunchie",
    TIE_DYE_TOTE_BAGES: "tieDyeToteBags",
    TIE_DYE_SOCKS: "tieDyeSocks"
}

export const CreationDisplayValues = {
    [Creations.FAIRY_BATH_BOMBS]: "Fairy Bath-Bombs",
    [Creations.GLITTER_FACE_PAINT]: "Glitter Face Paint",
    [Creations.RAINBOW_BATH_CRYSTALS]: "Rainbow Bath Crystals",
    [Creations.RAINBOW_SOAP]: "Rainbow Soap",
    [Creations.LIP_BALM]: "Sparkling Lip-Balm",
    [Creations.PERFUME]: "Shining Perfume",
    [Creations.SOAP]: "Sparkling Soap",
    [Creations.LAVA_LAMPS]: "Lava Lamps",
    [Creations.BUGS_IN_SOAP]: "Bugs in Soap",
    [Creations.BATH_BOMBS]: "Fizzy Bath Bombs",
    [Creations.GALAXY_SOAP]: "Galaxy Soap",
    [Creations.MONSTER_SLIME]: "Monster Slime",
    [Creations.WOBBLY_SOAP]: "Wobbly Soap",
    [Creations.FLUFFY_SLIME]: "Fluffy Slime",
    [Creations.GALAXY_SLIME]: "Galaxy Slime",
    [Creations.GLITTER_SLIME]: "Glitter Slime",
    [Creations.CRUNCHY_SLIME]: "Crunchy Slime",
    [Creations.FAIRY_SLIME]: "Fairy Slime",
    [Creations.EXPERT_GALAXY_SLIME]: "Expert Galaxy Slime",
    [Creations.EXPERT_RAINBOW_BATH_BOMBS]: "Expert Rainbow Bath-Bombs",
    [Creations.EXPERT_CRUNCHY_SLIME]: "Expert Crunchy Slime",
    [Creations.EXPERT_RAINBOW_SLIME]: "Expert Rainbow Slime",
    [Creations.EXPERT_RAINBOW_SOAP]: "Expert Rainbow Soap",
    [Creations.EXPERT_WATERMELON_BATH_BOMBS]: "Expert Watermelon Bath-Bombs",
    [Creations.EXPERT_GALAXY_BATH_BOMBS]: "Expert Galaxy Bath-Bombs",
    // added after website and packages rebuilt
    [Creations.UNICORN_SOAP]: "Unicorn Soap",
    [Creations.RAINBOW_BATH_BOMBS]: "Rainbow Bath Bombs",
    [Creations.VOLCANOES]: "Bubbling Volcanoes",
    [Creations.WOBBLY_GALAXY_SOAP]: "Wobbly Galaxy Soap",
    [Creations.INSTANT_SNOW_SLIME]: "Instant Snow Slime",
    [Creations.MAGIC_SAND]: "Magic Sand",
    [Creations.WOBBLY_STAR_SOAP]: "Wobbly Star Soap",
    [Creations.UNICORN_SLIME]: "Unicorn Slime",
    [Creations.RAINBOW_SLIME]: "Rainbow Slime",
    [Creations.FROZEN_SPARKLE_SLIME]: "Frozen Sparkle Slime",
    [Creations.ANIMALS_IN_SOAP]: "Animals in Soap",
    [Creations.LAVA_BATH_CRYSTALS]: "Lava Bath Crystals",
    [Creations.MAGIC_QUICK_SAND]: "Magic Quick Sand",
    [Creations.ANIMALS_IN_BATH_BOMBS]: "Animals in Bath Bombs",
    [Creations.UNICORN_GLITTER_SHIMMER]: "Unicorn Glitter Shimmer",
    [Creations.UNICORN_GALAXY_SLIME]: "Unicorn Galaxy Slime",
    [Creations.UNICORN_BATH_CRYSTALS]: "Unicorn Bath Crystals",
    [Creations.UNICORN_BATH_SHIMMER]: "Unicorn Bath Shimmer",
    [Creations.UNICORN_BUBBLE_BATH]: "Unicorn Bubble Bath",
    [Creations.BUTTERFLY_SOAP]: "Butterfly Soap",
    [Creations.UNICORN_BATH_BOMBS]: "Unicorn Bath Bombs",
    [Creations.TIE_DYE_SOAP]: "Tie Dye Soap",
    [Creations.TIE_DYE_PILLOW]: "Tie Dye Pillow",
    [Creations.MARBLE_CRYSTALS]: "Marble Crystals",
    [Creations.TIE_DYE_SCRUNCHIE]: "Tie Dye Scrunchie",
    [Creations.TIE_DYE_TOTE_BAGES]: "Tie Dye Tote Bags",
    [Creations.TIE_DYE_SOCKS]: "Tie Dye Socks"
}