export const fields = {
    PARENT_FIRST_NAME: "parentFirstName",
    PARENT_LAST_NAME: "parentLastName",
    PARENT_EMAIL: "parentEmail",
    PARENT_MOBILE: "parentMobile",
    CHILD_NAME: "childName",
    CHILD_AGE: "childAge",
    DATE: "date",
    TIME: "time",
    LOCATION: "location",
    PARTY_LENGTH: "partyLength",
    ADDRESS: "address",
    NOTES: "notes",
    CREATION_1: "creation1",
    CREATION_2: "creation2",
    CREATION_3: "creation3",
    CAKE: "cake",
    CAKE_FLAVOUR: "cakeFlavour",
    QUESTIONS: "questions"
}

export const additions = {
    CHICKEN_NUGGETS: "chickenNuggets",
    FAIRY_BREAD: "fairyBread",
    FRUIT_PLATTER: "fruitPlatter",
    SANDWICH_PLATTER: "sandwichPlatter",
    VEGGIE_PLATTER: "veggiePlatter",
    WATERMELON_PLATTER: "watermelonPlatter",
    WEDGES: "wedges",
    LOLLY_BAGS: "lollyBags"
}

export const creations = {
    FAIRY_BATH_BOMBS: "fairyBathBombs",
    GLITTER_FACE_PAINT: "glitterFacePaint",
    RAINBOW_BATH_CRYSTALS: "rainbowBathCrystals",
    RAINBOW_SOAP: "rainbowSoap",
    LIP_BALM: "lipBalm",
    PERFUME: "perfume",
    SOAP: "soap",
    LAVA_LAMPS: "lavaLamps",
    BUGS_IN_SOAP: "bugsInSoap",
    BATH_BOMBS: "bathBombs",
    GALAXY_SOAP: "galaxySoap",
    WOBBLY_SOAP: "wobblySoap",
    MONSTER_SLIME: "monsterSlime",
    FLUFFY_SLIME: "fluffySlime",
    GALAXY_SLIME: "galaxySlime",
    GLITTER_SLIME: "glitterSlime",
    CRUNCHY_SLIME: "crunchySlime",
    FAIRY_SLIME: "fairySlime",
    EXPERT_GALAXY_SLIME: "expertGalaxySlime",
    EXPERT_RAINBOW_BATH_BOMBS: "expertRainbowBathBombs",
    EXPERT_CRUNCHY_SLIME: "expertCrunchySlime",
    EXPERT_RAINBOW_SLIME: "expertRainbowSlime",
    EXPERT_RAINBOW_SOAP: "expertRainbowSoap",
    EXPERT_WATERMELON_BATH_BOMBS: "expertWatermelonBathBombs",
    EXPERT_GALAXY_BATH_BOMBS: "expertGalaxyBathBombs"
}

export const creationDisplayValues = {
    [creations.FAIRY_BATH_BOMBS]: "Fairy Bath-Bombs",
    [creations.GLITTER_FACE_PAINT]: "Glitter Face Paint",
    [creations.RAINBOW_BATH_CRYSTALS]: "Rainbow Bath Crystals",
    [creations.RAINBOW_SOAP]: "Rainbow Soap",
    [creations.LIP_BALM]: "Sparkling Lip-Balm",
    [creations.PERFUME]: "Shining Perfume",
    [creations.SOAP]: "Sparkling Soap",
    [creations.LAVA_LAMPS]: "Bubbling Lava Lamps",
    [creations.BUGS_IN_SOAP]: "Bugs in Soap",
    [creations.BATH_BOMBS]: "Fizzing Bath-Bombs",
    [creations.GALAXY_SOAP]: "Galaxy Soap",
    [creations.MONSTER_SLIME]: "Monster Slime",
    [creations.WOBBLY_SOAP]: "Wobbly Soap",
    [creations.FLUFFY_SLIME]: "Fluffy Slime",
    [creations.GALAXY_SLIME]: "Galaxy Slime",
    [creations.GLITTER_SLIME]: "Glitter Slime",
    [creations.CRUNCHY_SLIME]: "Crunchy Slime",
    [creations.FAIRY_SLIME]: "Fairy Slime",
    [creations.EXPERT_GALAXY_SLIME]: "Expert Galaxy Slime",
    [creations.EXPERT_RAINBOW_BATH_BOMBS]: "Expert Rainbow Bath-Bombs",
    [creations.EXPERT_CRUNCHY_SLIME]: "Expert Crunchy Slime",
    [creations.EXPERT_RAINBOW_SLIME]: "Expert Rainbow Slime",
    [creations.EXPERT_RAINBOW_SOAP]: "Expert Rainbow Soap",
    [creations.EXPERT_WATERMELON_BATH_BOMBS]: "Expert Watermelon Bath-Bombs",
    [creations.EXPERT_GALAXY_BATH_BOMBS]: "Expert Galaxy Bath-Bombs"
}