name: Deploy (develop & pipelines)

on:
  push:
    branches: [develop, pipelines]
    paths:
      - "client/**"
      - "server/**"
      - "firebase.json"
      - ".firebaserc"
      - "client/predeploy.sh"
      - ".github/workflows/deploy-develop.yml"

  # Manual trigger from the Actions tab
  workflow_dispatch:

concurrency:
  group: deploy-develop
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Use GitHub Environments so env-scoped secrets/approvals apply
    environment: "dev"
    permissions:
      contents: read

    env:
      PROJECT_ID: booking-system-6435d

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
            server/fizz-kidz/package-lock.json

      # Ensure local package builds have their toolchains
      - name: Install dependencies (fizz-kidz)
        run: npm ci
        working-directory: server/fizz-kidz

      - name: Install dependencies (server)
        run: npm ci
        working-directory: server

      - name: Install dependencies (client)
        run: npm ci
        working-directory: client

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Functions and Hosting (develop)
        env:
          GCLOUD_PROJECT: ${{ env.PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy \
            --only functions,hosting \
            --project "$PROJECT_ID" \
            --token "$FIREBASE_TOKEN" \
            --non-interactive \
            --force
