import { Creation } from './Creation'

export type CreationKeyMap = { [key in keyof typeof Creation]: string }

export const CreationDisplayValuesMap: CreationKeyMap = {
    [Creation.fairyBathBombs]: "Fairy Bath-Bombs",
    [Creation.glitterFacePaint]: "Glitter Face Paint",
    [Creation.rainbowBathCrystals]: "Rainbow Bath Crystals",
    [Creation.rainbowSoap]: "Rainbow Soap",
    [Creation.lipBalm]: "Sparkling Lip-Balm",
    [Creation.perfume]: "Shining Perfume",
    [Creation.soap]: "Sparkling Soap",
    [Creation.lavaLamps]: "Lava Lamps",
    [Creation.bugsInSoap]: "Bugs in Soap",
    [Creation.bathBombs]: "Fizzy Bath Bombs",
    [Creation.galaxySoap]: "Galaxy Soap",
    [Creation.monsterSlime]: "Monster Slime",
    [Creation.wobblySoap]: "Wobbly Soap",
    [Creation.fluffySlime]: "Fluffy Slime",
    [Creation.galaxySlime]: "Galaxy Slime",
    [Creation.glitterSlime]: "Glitter Slime",
    [Creation.crunchySlime]: "Crunchy Slime",
    [Creation.fairySlime]: "Fairy Glitter Slime",
    [Creation.expertGalaxySlime]: "Expert Galaxy Slime",
    [Creation.expertRainbowBathBombs]: "Expert Rainbow Bath-Bombs",
    [Creation.expertCrunchySlime]: "Expert Crunchy Slime",
    [Creation.expertRainbowSlime]: "Expert Rainbow Slime",
    [Creation.expertRainbowSoap]: "Expert Rainbow Soap",
    [Creation.expertWatermelonBathBombs]: "Expert Watermelon Bath-Bombs",
    [Creation.expertGalaxyBathBombs]: "Expert Galaxy Bath-Bombs",
    // added after website and packages rebuilt
    [Creation.unicornSoap]: "Unicorn Soap",
    [Creation.rainbowBathBombs]: "Rainbow Bath Bombs",
    [Creation.volcanoes]: "Bubbling Volcanoes",
    [Creation.wobblyGalaxySoap]: "Wobbly Galaxy Soap",
    [Creation.instantSnowSlime]: "Instant Snow Slime",
    [Creation.magicSand]: "Magic Sand",
    [Creation.wobblyStarSoap]: "Wobbly Star Soap",
    [Creation.unicornSlime]: "Unicorn Slime",
    [Creation.rainbowSlime]: "Rainbow Slime",
    [Creation.frozenSparkleSlime]: "Frozen Sparkle Slime",
    [Creation.animalsInSoap]: "Animals in Soap",
    [Creation.lavaBathCrystals]: "Lava Bath Crystals",
    [Creation.magicQuickSand]: "Magic Quick Sand",
    [Creation.animalsInBathBombs]: "Animals in Bath Bombs",
    [Creation.unicornGlitterShimmer]: "Unicorn Glitter Shimmer",
    [Creation.unicornGalaxySlime]: "Unicorn Galaxy Slime",
    [Creation.unicornBathCrystals]: "Unicorn Bath Crystals",
    [Creation.unicornBathShimmer]: "Unicorn Bath Shimmer",
    [Creation.unicornBubbleBath]: "Unicorn Bubble Bath",
    [Creation.butterflySoap]: "Butterfly Soap",
    [Creation.unicornBathBombs]: "Unicorn Bath Bombs",
    [Creation.tieDyeSoap]: "Tie Dye Soap",
    [Creation.tieDyePillow]: "Tie Dye Pillow",
    [Creation.marbleCrystals]: "Marble Crystals",
    [Creation.tieDyeScrunchie]: "Tie Dye Scrunchie",
    [Creation.tieDyeToteBags]: "Tie Dye Tote Bags",
    [Creation.tieDyeSocks]: "Tie Dye Socks"
}